import Head from "next/head";
import Image from "next/image";

import Nav from "components/nav";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Gérmes</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav></Nav>
            <main>hello</main>
            <style jsx>{`
                main {
                    width: 100vw;
                    height: 100vh;
                    background-color: green;
                }
            `}</style>

            <style global jsx>{`
                * {
                    margin: 0;
                    padding: 0;
                    box-sizing: border-box;
                }
            `}</style>
        </div>
    );
}
